### ISSUE TITLE
Getting database error 

### ISSUE THREAD

**Issue by NaziYeeter** [TeztechYT/Telegram-Member-Adder#1]
Traceback (most recent call last):
  File "/anonymous/__anon__
    client = TelegramClient(f"sessions/{phone}", api_id, api_hash)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/telethon/client/telegrambaseclient.py", line 262, in __init__
    session = SQLiteSession(session)                              File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/telethon/sessions/sqlite.py", line 47, in __init__              c = self._cursor()                                            File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/telethon/sessions/sqlite.py", line 228, in _cursor
    self._conn = sqlite3.connect(self.filename,                 sqlite3.OperationalError: unable to open database file

**Comment by NaziYeeter** [comment]
Fixes by changing Sessions to session 💪

**Comment by NaziYeeter** [comment]
Is there any example on how to format csv file i keep getting error on second number

**Comment by TeztechYT** [comment]
> Is there any example on how to format csv file i keep getting error on second number

open that csv file which you want to format in any notepad then clear the text and save changes

**Comment by TeztechYT** [comment]
> Traceback (most recent call last):
> File "/anonymous/**anon**
> client = TelegramClient(f"sessions/{phone}", api_id, api_hash)
> File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/telethon/client/telegrambaseclient.py", line 262, in **init**
> session = SQLiteSession(session) File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/telethon/sessions/sqlite.py", line 47, in **init** c = self._cursor() File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/telethon/sessions/sqlite.py", line 228, in _cursor
> self._conn = sqlite3.connect(self.filename, sqlite3.OperationalError: unable to open database file

keep patience readme.txt was not completed

**Comment by NaziYeeter** [comment]
Alright thanks

**Comment by TeztechYT** [comment]
Now try brother and don't forget to create a empty folder named 'sessions'

**Comment by NaziYeeter** [comment]
Does it read old session?? Or can you make it does

**Comment by NaziYeeter** [comment]
deltaop = list_of_rows[row_number - 1][col_number - 1]
IndexError: list index out of range

**Comment by tejkirar** [comment]
> Does it read old session?? Or can you make it does

Yes !!

**Comment by NaziYeeter** [comment]
Thanks for helping me ❤️
